services:
    node:
        build: .
        container_name: 2d-frame-node
        command: "${SERVER_RUN_COMMAND:-yarn static-server}"
        volumes:
            - ./src:/app/src
        ports:
            - 8001:8001
